HTTP/1.0 200 OK
Content-Type:text/xml

<?xml version="1.0" standalone="yes" ?><!DOCTYPE SHOUTCASTSERVER [<!ELEMENT SHOUTCASTSERVER (CURRENTLISTENERS,PEAKLISTENERS,MAXLISTENERS,REPORTEDLISTENERS,AVERAGETIME,SERVERGENRE,SERVERURL,SERVERTITLE,SONGTITLE,SONGURL,IRC,ICQ,AIM,WEBHITS,STREAMHITS,STREAMSTATUS,BITRATE,CONTENT,VERSION,WEBDATA,LISTENERS,SONGHISTORY)><!ELEMENT CURRENTLISTENERS (#PCDATA)><!ELEMENT PEAKLISTENERS (#PCDATA)><!ELEMENT MAXLISTENERS (#PCDATA)><!ELEMENT REPORTEDLISTENERS (#PCDATA)><!ELEMENT AVERAGETIME (#PCDATA)><!ELEMENT SERVERGENRE (#PCDATA)><!ELEMENT SERVERURL (#PCDATA)><!ELEMENT SERVERTITLE (#PCDATA)><!ELEMENT SONGTITLE (#PCDATA)><!ELEMENT SONGURL (#PCDATA)><!ELEMENT IRC (#PCDATA)><!ELEMENT ICQ (#PCDATA)><!ELEMENT AIM (#PCDATA)><!ELEMENT WEBHITS (#PCDATA)><!ELEMENT STREAMHITS (#PCDATA)><!ELEMENT STREAMSTATUS (#PCDATA)><!ELEMENT BITRATE (#PCDATA)><!ELEMENT CONTENT (#PCDATA)><!ELEMENT VERSION (#PCDATA)><!ELEMENT WEBDATA (INDEX,LISTEN,PALM7,LOGIN,LOGINFAIL,PLAYED,COOKIE,ADMIN,UPDINFO,KICKSRC,KICKDST,UNBANDST,BANDST,VIEWBAN,UNRIPDST,RIPDST,VIEWRIP,VIEWXML,VIEWLOG,INVALID)><!ELEMENT INDEX (#PCDATA)><!ELEMENT LISTEN (#PCDATA)><!ELEMENT PALM7 (#PCDATA)><!ELEMENT LOGIN (#PCDATA)><!ELEMENT LOGINFAIL (#PCDATA)><!ELEMENT PLAYED (#PCDATA)><!ELEMENT COOKIE (#PCDATA)><!ELEMENT ADMIN (#PCDATA)><!ELEMENT UPDINFO (#PCDATA)><!ELEMENT KICKSRC (#PCDATA)><!ELEMENT KICKDST (#PCDATA)><!ELEMENT UNBANDST (#PCDATA)><!ELEMENT BANDST (#PCDATA)><!ELEMENT VIEWBAN (#PCDATA)><!ELEMENT UNRIPDST (#PCDATA)><!ELEMENT RIPDST (#PCDATA)><!ELEMENT VIEWRIP (#PCDATA)><!ELEMENT VIEWXML (#PCDATA)><!ELEMENT VIEWLOG (#PCDATA)><!ELEMENT INVALID (#PCDATA)><!ELEMENT LISTENERS (LISTENER*)><!ELEMENT LISTENER (HOSTNAME,USERAGENT,UNDERRUNS,CONNECTTIME, POINTER, UID)><!ELEMENT HOSTNAME (#PCDATA)><!ELEMENT USERAGENT (#PCDATA)><!ELEMENT UNDERRUNS (#PCDATA)><!ELEMENT CONNECTTIME (#PCDATA)><!ELEMENT POINTER (#PCDATA)><!ELEMENT UID (#PCDATA)><!ELEMENT SONGHISTORY (SONG*)><!ELEMENT SONG (PLAYEDAT, TITLE)><!ELEMENT PLAYEDAT (#PCDATA)><!ELEMENT TITLE (#PCDATA)>]><SHOUTCASTSERVER><CURRENTLISTENERS>4</CURRENTLISTENERS><PEAKLISTENERS>4</PEAKLISTENERS><MAXLISTENERS>32</MAXLISTENERS><REPORTEDLISTENERS>1</REPORTEDLISTENERS><AVERAGETIME>122</AVERAGETIME><SERVERGENRE>Pop</SERVERGENRE><SERVERURL>http://templateshares.net</SERVERURL><SERVERTITLE>Templateshares</SERVERTITLE><SONGTITLE>www.e-dana.com - Tarkan 2006  - Shhh</SONGTITLE><SONGURL></SONGURL><IRC>#shoutcast</IRC><ICQ>0</ICQ><AIM>N/A</AIM><WEBHITS>18</WEBHITS><STREAMHITS>10</STREAMHITS><STREAMSTATUS>1</STREAMSTATUS><BITRATE>24</BITRATE><CONTENT>audio/mpeg</CONTENT><VERSION>1.9.8</VERSION><WEBDATA><INDEX>4</INDEX><LISTEN>2</LISTEN><PALM7>0</PALM7><LOGIN>0</LOGIN><LOGINFAIL>0</LOGINFAIL><PLAYED>0</PLAYED><COOKIE>0</COOKIE><ADMIN>0</ADMIN><UPDINFO>6</UPDINFO><KICKSRC>0</KICKSRC><KICKDST>0</KICKDST><UNBANDST>0</UNBANDST><BANDST>0</BANDST><VIEWBAN>0</VIEWBAN><UNRIPDST>0</UNRIPDST><RIPDST>0</RIPDST><VIEWRIP>0</VIEWRIP><VIEWXML>6</VIEWXML><VIEWLOG>0</VIEWLOG><INVALID>0</INVALID></WEBDATA><LISTENERS><LISTENER><HOSTNAME>77.251.3.79</HOSTNAME><USERAGENT>WinampMPEG/2.8</USERAGENT><UNDERRUNS>0</UNDERRUNS><CONNECTTIME>199</CONNECTTIME><POINTER>0</POINTER><UID>5</UID></LISTENER><LISTENER><HOSTNAME>77.251.3.79</HOSTNAME><USERAGENT>WinampMPEG/2.8</USERAGENT><UNDERRUNS>0</UNDERRUNS><CONNECTTIME>199</CONNECTTIME><POINTER>1</POINTER><UID>6</UID></LISTENER><LISTENER><HOSTNAME>77.251.3.79</HOSTNAME><USERAGENT>WinampMPEG/2.8</USERAGENT><UNDERRUNS>0</UNDERRUNS><CONNECTTIME>152</CONNECTTIME><POINTER>2</POINTER><UID>8</UID></LISTENER><LISTENER><HOSTNAME>77.251.3.79</HOSTNAME><USERAGENT>WinampMPEG/2.8</USERAGENT><UNDERRUNS>0</UNDERRUNS><CONNECTTIME>152</CONNECTTIME><POINTER>3</POINTER><UID>9</UID></LISTENER></LISTENERS><SONGHISTORY><SONG><PLAYEDAT>1232528059</PLAYEDAT><TITLE>www.e-dana.com - Tarkan 2006  - Shhh</TITLE></SONG><SONG><PLAYEDAT>1232527857</PLAYEDAT><TITLE>www.e-dana.com - Tarkan 2006  - Mine</TITLE></SONG><SONG><PLAYEDAT>1232527547</PLAYEDAT><TITLE>WestSide Connection - 3 Time Felons</TITLE></SONG><SONG><PLAYEDAT>1232527341</PLAYEDAT><TITLE>www.e-dana.com - Tarkan 2006 - If Only You Knew</TITLE></SONG><SONG><PLAYEDAT>1232527162</PLAYEDAT><TITLE>www.e-dana.com - Tarkan 2006 - I,m Gonna Make U Feel Good</TITLE></SONG><SONG><PLAYEDAT>1232526955</PLAYEDAT><TITLE>www.e-dana.com - Tarkan 2006 - If Only You Knew</TITLE></SONG></SONGHISTORY></SHOUTCASTSERVER>